Netlist(Freeze)
Netlist(Clear)
Netlist(Add,+12VD,S1-2)
Netlist(Add,+12VD,C1-1)
Netlist(Add,+12VD,CONN4-9)
Netlist(Add,+12VD,CONN3-9)
Netlist(Add,unnamed_net8,CONN4-7)
Netlist(Add,unnamed_net8,CONN3-7)
Netlist(Add,+15V,CONN4-5)
Netlist(Add,+15V,CONN3-5)
Netlist(Add,unnamed_net7,CONN4-3)
Netlist(Add,unnamed_net7,CONN3-3)
Netlist(Add,Chassis,S1-4)
Netlist(Add,Chassis,S1-5)
Netlist(Add,Chassis,CONN4-1)
Netlist(Add,Chassis,CONN3-1)
Netlist(Add,unnamed_net6,CONN4-6)
Netlist(Add,unnamed_net6,CONN3-6)
Netlist(Add,-15V,CONN4-4)
Netlist(Add,-15V,CONN3-4)
Netlist(Add,COM,CONN4-2)
Netlist(Add,COM,CONN3-2)
Netlist(Add,unnamed_net5,C2-1)
Netlist(Add,unnamed_net5,Q1-2)
Netlist(Add,unnamed_net5,MOD1-1)
Netlist(Add,unnamed_net4,Q1-1)
Netlist(Add,unnamed_net4,R2-2)
Netlist(Add,unnamed_net4,Z1-1)
Netlist(Add,unnamed_net4,R3-2)
Netlist(Add,unnamed_net4,R1-1)
Netlist(Add,unnamed_net3,C2-2)
Netlist(Add,unnamed_net3,MOD1-2)
Netlist(Add,unnamed_net3,S1-1)
Netlist(Add,unnamed_net3,D1-1)
Netlist(Add,unnamed_net2,R1-2)
Netlist(Add,unnamed_net2,S1-3)
Netlist(Add,unnamed_net2,D1-2)
Netlist(Add,unnamed_net1,R3-1)
Netlist(Add,unnamed_net1,CONN1-1)
Netlist(Add,GND,Q1-3)
Netlist(Add,GND,C1-2)
Netlist(Add,GND,CONN4-8)
Netlist(Add,GND,CONN3-8)
Netlist(Add,GND,R2-1)
Netlist(Add,GND,Z1-2)
Netlist(Add,GND,CONN1-2)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"S1","7107P3CWAV2QE22.fp","unknown")
ElementSetAttr("S1","device","unknown")
ElementSetAttr("S1","manufacturer","unknown")
ElementSetAttr("S1","manufacturer_part_number","unknown")
ElementSetAttr("S1","vendor","unknown")
ElementSetAttr("S1","vendor_part_number","unknown")
ChangePinName("S1", 5, "5")
ChangePinName("S1", 4, "4")
ChangePinName("S1", 2, "2")
ChangePinName("S1", 3, "3")
ChangePinName("S1", 1, "1")
ElementList(Need,"Q1","TO220SW","unknown")
ElementSetAttr("Q1","device","unknown")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 1, "G")
ChangePinName("Q1", 3, "S")
ChangePinName("Q1", 2, "D")
ElementList(Need,"C2","rcy(100mil, dia=200, pol=none)","0.1uF")
ElementSetAttr("C2","device","CAPACITOR")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"C1","rcy(100.00mil, pol=bar-sign, dia=200)","100uF")
ElementSetAttr("C1","device","POLARIZED_CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "-")
ChangePinName("C1", 1, "+")
ElementList(Need,"CONN4","molex-22-23-2091-mini_9_vert.fp","126-220")
ElementSetAttr("CONN4","device","CONNECTOR_9")
ElementSetAttr("CONN4","manufacturer","unknown")
ElementSetAttr("CONN4","manufacturer_part_number","unknown")
ElementSetAttr("CONN4","vendor","unknown")
ElementSetAttr("CONN4","vendor_part_number","unknown")
ChangePinName("CONN4", 9, "9")
ChangePinName("CONN4", 7, "7")
ChangePinName("CONN4", 5, "5")
ChangePinName("CONN4", 3, "3")
ChangePinName("CONN4", 1, "1")
ChangePinName("CONN4", 8, "8")
ChangePinName("CONN4", 6, "6")
ChangePinName("CONN4", 4, "4")
ChangePinName("CONN4", 2, "2")
ElementList(Need,"CONN3","molex-22-05-3091-mini_9_ra.fp","126-221")
ElementSetAttr("CONN3","device","CONNECTOR_9")
ElementSetAttr("CONN3","manufacturer","unknown")
ElementSetAttr("CONN3","manufacturer_part_number","unknown")
ElementSetAttr("CONN3","vendor","unknown")
ElementSetAttr("CONN3","vendor_part_number","unknown")
ChangePinName("CONN3", 9, "9")
ChangePinName("CONN3", 7, "7")
ChangePinName("CONN3", 5, "5")
ChangePinName("CONN3", 3, "3")
ChangePinName("CONN3", 1, "1")
ChangePinName("CONN3", 8, "8")
ChangePinName("CONN3", 6, "6")
ChangePinName("CONN3", 4, "4")
ChangePinName("CONN3", 2, "2")
ElementList(Need,"MOD1","acy(1000)","unknown")
ElementSetAttr("MOD1","device","RESISTOR")
ElementSetAttr("MOD1","manufacturer","unknown")
ElementSetAttr("MOD1","manufacturer_part_number","unknown")
ElementSetAttr("MOD1","vendor","unknown")
ElementSetAttr("MOD1","vendor_part_number","unknown")
ChangePinName("MOD1", 1, "1")
ChangePinName("MOD1", 2, "2")
ElementList(Need,"R2","acy(400, type=zigzag)","100K")
ElementSetAttr("R2","device","RESISTOR")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"Z1","alf(400, zener)","unknown")
ElementSetAttr("Z1","device","ZENER_DIODE")
ElementSetAttr("Z1","manufacturer","unknown")
ElementSetAttr("Z1","manufacturer_part_number","unknown")
ElementSetAttr("Z1","vendor","unknown")
ElementSetAttr("Z1","vendor_part_number","unknown")
ChangePinName("Z1", 2, "2")
ChangePinName("Z1", 1, "1")
ElementList(Need,"R3","acy(400, type=zigzag)","10K")
ElementSetAttr("R3","device","RESISTOR")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"R1","acy(400, type=zigzag)","10K")
ElementSetAttr("R1","device","RESISTOR")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"D1","alf(400)","unknown")
ElementSetAttr("D1","device","DIODE")
ElementSetAttr("D1","manufacturer","unknown")
ElementSetAttr("D1","manufacturer_part_number","unknown")
ElementSetAttr("D1","vendor","unknown")
ElementSetAttr("D1","vendor_part_number","unknown")
ChangePinName("D1", 1, "1")
ChangePinName("D1", 2, "2")
ElementList(Need,"CONN1","AMPHENOL_BNC_31-5431-ver2.fp","unknown")
ElementSetAttr("CONN1","device","BNC")
ElementSetAttr("CONN1","manufacturer","unknown")
ElementSetAttr("CONN1","manufacturer_part_number","unknown")
ElementSetAttr("CONN1","vendor","unknown")
ElementSetAttr("CONN1","vendor_part_number","unknown")
ChangePinName("CONN1", 1, "1")
ChangePinName("CONN1", 2, "2")
ElementList(Done)
